local_costmap:
  plugins: []
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 2.5
  publish_frequency: 2.5
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.1
