transform_tolerance: 0.2  # 0.2
obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[0.08, 0.05], [0.08, -0.05], [-0.08, -0.05], [-0.08, 0.05]]
inflation_layer:
  inflation_radius: 6.  # the bigger the better, defines where the gradient is
  cost_scaling_factor: 0.9 
#static_layer:
# unknown_cost_value: -1
#  lethal_cost_threshold: 254
#  first_map_only: true
#  subscribe_to_updates: false
#  track_unknown_space: true
#  use_maximum: true
#  trinary_costmap: true


#inflation_layer:
#  inflation_radius: 30.  # the bigger the better, defines where the gradient is
#  cost_scaling_factor: 0.9  # 0.5 the bigger the steeper the gradient is

observation_sources: laser_scan_sensor #point_cloud_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: priv2/laser/scan, marking: true, clearing: true}

#depth_obstacle_layer:
#   observation_sources: point_cloud_kinect        
#    track_unknown_space: false
#    footprint_clearing_enabled: true
#   combination_method: 1  # 0 - overwrite, 1 - max, 99 - nothing
        
#    point_cloud_kinect:
#        sensor_frame: depth_camera_optical
#        data_type: PointCloud2
#        topic: /mark1/depth/points
#        marking: true
#        clearing: true
#        min_obstacle_height: 0.1
#        max_obstacle_height: 0.8
#        obstacle_range: 4.
#        raytrace_range: 5v.
