local_costmap:
  plugins: []
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 2.
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.5
  map_type: costmap
