transform_tolerance: 0.55  # 0.2
obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[0.09, 0.06], [0.09, -0.06], [-0.09, -0.06], [-0.09, 0.06]]
inflation_layer:
  inflation_radius: 0.3 
  cost_scaling_factor: 2 
static_layer:
  unknown_cost_value: -1
  lethal_cost_threshold: 254
  first_map_only: true
  subscribe_to_updates: false
  track_unknown_space: true
  use_maximum: true
  trinary_costmap: true


observation_sources: laser_scan_sensor #point_cloud_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: priv2/laser/scan, marking: true, clearing: true}


