base_global_planner: "global_planner/GlobalPlanner"
controller_frequency: 2
  
planner_frequency: 0.  # 0. is only plan on a new goal or when local planner fails
planner_patience: 2.
controller_patience: 15.
recovery_behavior_enables: true
shutdown_costmaps: false
oscillation_timeout: 0.  # 0. is infinite
oscillation_distance: 0.5
map_planning_retries: -1.

TrajectoryPlannerROS:
  
  dwa: true
  global_frame_id: odom

  
  acc_lim_theta: 5
  max_vel_x: 0.5
  min_vel_x: 0.1

  max_rotational_vel: 1
  min_in_place_vel_theta: 0.8

  max_vel_theta: 2
  min_vel_theta: -2

  # goal
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.3

  # other
  holonomic_robot: false
  meter_scoring: false

  sim_granularity: 0.001
  

GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.
  visualize_potential: true
  use_dijkstra: true  # although A* is faster, implementation pecularities here make it undesirable
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  lethal_cost: 253 #253 # how far from obstacle
  neutral_cost: 66 #40
  cost_factor:  3 #3
  publish_potential: True
  orientation_mode: 0.
  orientation_window_size: 1
